{
 "bad": false,
 "new_version": "5.9.14-next",
 "new_version_attempts": {
  "5.8.0": 1,
  "5.9.14-next": 121,
  "5.9.4-next": 3,
  "5.9.8-next": 14,
  "5.9.9-next": 2
 },
 "new_version_errors": {
  "5.9.14-next": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/10431372333\">bot CI job</a>): main:\nError running rerender-feedstock in container - error RuntimeError raised:\n'Failed to rerender.\noutput: Adding in variants from internal_defaults\nAdding in variants from /tmp/tmptvjty1gk/conda-smithy/conda_build_config.yaml\nINFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2024.08.17.00.11.41\nINFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmptvjty1gk/conda-smithy\nINFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped\nINFO:conda_smithy.configure_feedstock:README rendering is skipped\nWARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.\nWARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.\nWARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 758, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 601, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 604, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2770, in main\n    render_travis(env, config, forge_dir, return_metadata=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1542, in render_travis\n    return _render_ci_provider(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1085, in _render_ci_provider\n    metas = _conda_build_api_render_for_smithy(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 885, in _conda_build_api_render_for_smithy\n    metadata_tuples = render_recipe(\n                      ^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/render.py\", line 971, in render_recipe\n    m.config.compute_build_id(m.name(), m.version(), reset=reset_build_id)\n                                        ^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 1531, in version\n    check_bad_chrs(version, \"package/version\")\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 783, in check_bad_chrs\n    raise CondaBuildUserError(\nconda_build.exceptions.CondaBuildUserError: Bad character(s) (-) in package/version: 5.9.14-next.\n\n'"
 }
}