{
  "_feedstock_status": {
    "ffmpeg": {
      "immediate_children": [
        "opencv"
      ],
      "num_descendants": 1,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/ffmpeg-feedstock",
      "pre_pr_migrator_status": ""
    },
    "opencv": {
      "immediate_children": [],
      "num_descendants": 0,
      "pre_pr_migrator_status": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/10434120245\">bot CI job</a>): main:\nError running rerender-feedstock in container - error RuntimeError raised:\n'Failed to rerender.\noutput: Traceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 758, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 601, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 604, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2740, in main\n    exclusive_config_file, cf_pinning_ver = get_cached_cfp_file_path(\n                                            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2553, in get_cached_cfp_file_path\n    current_pinning_version = get_most_recent_version(\n                              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2426, in get_most_recent_version\n    request.raise_for_status()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 524 Server Error:  for url: https://api.anaconda.org/package/conda-forge/conda-forge-pinning\n\n'"
    },
    "openvino-tokenizers": {
      "immediate_children": [],
      "num_descendants": 0,
      "pr_status": "",
      "pr_url": "https://github.com/conda-forge/openvino-tokenizers-feedstock",
      "pre_pr_migrator_status": ""
    }
  },
  "awaiting-parents": [],
  "awaiting-pr": [],
  "bot-error": [
    "opencv"
  ],
  "done": [
    "openvino-tokenizers",
    "ffmpeg"
  ],
  "in-pr": [],
  "not-solvable": []
}